version: '3.1'

services:

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edexme_project
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
      - redis
    environment:
      - MYSQL_DATABASE_URL=mysql+pymysql://edexme:SHzeQizz@mariadb:3306/edexme_db
      - ADMIN_SECRET_KEY=SjhOIhpo9OHHUOuipIutftf&d\cAJ0bbHJGHYT687gu8*hjihuk9JQgFDJrp4Fdbk0o|?
      - SECRET_KEY=puwar0eqmh2tBMqXBEE/cAJ0bbFufsNKQLCMO463qY4hOk9JQgFDJrp4Fdbk0oK
      - ALGORITHM=HS256
      - TIME=43200
      - COMPANY_EMAIL=edexmehelp@gmail.com
      - COMPANY_EMAIL_PASSWORD=cogg cfvz unyc lmgl
      - TZ=Asia/Colombo

    volumes:
      - .:/app
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: edexme_mariadb_DB
    environment:
      MYSQL_ROOT_PASSWORD: SHzeQizz
      MYSQL_DATABASE: edexme_db
      MYSQL_USER: edexme
      MYSQL_PASSWORD: SHzeQizz
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  redis:
    image: redis:latest
    container_name: edexme_redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  caddy:
    image: caddy:latest
    container_name: caddy_web_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./website:/var/www/website
    restart: always
    depends_on:
      - fastapi_app



volumes:
  mariadb_data:
  redis_data:
  caddy_data:
  caddy_config:
